# Generated by Django 4.1.6 on 2023-04-06 17:08

import ApplicationCore.Services.DB.interface.IDBEntity
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            bases=(models.Model, ApplicationCore.Services.DB.interface.IDBEntity.IDBEntity),
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('px', models.FloatField()),
                ('qty', models.FloatField()),
                ('num', models.IntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CryptoStatistics.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Asks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('px', models.FloatField()),
                ('qty', models.FloatField()),
                ('num', models.IntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CryptoStatistics.symbol')),
            ],
            bases=(models.Model, ApplicationCore.Services.DB.interface.IDBEntity.IDBEntity),
        ),
    ]
